### ISSUE TITLE
Sound settings crashes on startup

### ISSUE THREAD

**Issue by GiltosMx** [elementary/switchboard-plug-sound#48] opened 2018-01-24 19:16 UTC
Whenever I try to open the sound settings, the app crashes and I have to force quit. Not very sure why this happens, but I included the error and GDB's backtrace.

```
adrian@Adrian-ENVY: gdb switchboard
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
(gdb) r
Starting program: /usr/bin/switchboard 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe48cf700 (LWP 13951)]
[New Thread 0x7fffdfb90700 (LWP 13952)]
[INFO 12:38:01.771463] Application.vala:154: System Settings version: 2.0
[INFO 12:38:01.771528] Application.vala:156: Kernel version: 4.4.0-112-generic
[New Thread 0x7fffd6db0700 (LWP 13953)]
[New Thread 0x7fffc84db700 (LWP 13956)]
[New Thread 0x7fffc6ebd700 (LWP 13957)]
[WARNING 12:38:04.540766] [GLib-GObject] cannot register existing type 'NMSetting'
[FATAL 12:38:04.540812] [GLib] g_once_init_leave: assertion 'result != 0' failed
[FATAL 12:38:04.540843] [GLib-GObject] g_type_register_static: assertion 'parent_type > 0' failed
[FATAL 12:38:04.540859] [libnm-util] _nm_register_setting: assertion 'type != G_TYPE_INVALID' failed
[FATAL 12:38:04.540873] [GLib] g_once_init_leave: assertion 'result != 0' failed
^C
Thread 1 "switchboard" received signal SIGINT, Interrupt.
syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
38	../sysdeps/unix/sysv/linux/x86_64/syscall.S: No such file or directory.
(gdb) bt
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007ffff6037bdf in g_cond_wait () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff6019d0b in g_once_init_enter () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fffb86a6778 in nm_setting_get_type () from /usr/lib/x86_64-linux-gnu/libnm-util.so.2
#4  0x00007fffb86af76d in nm_setting_adsl_get_type () from /usr/lib/x86_64-linux-gnu/libnm-util.so.2
#5  0x00007fffb869f349 in ?? () from /usr/lib/x86_64-linux-gnu/libnm-util.so.2
#6  0x00007ffff7de76ba in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7fffffffdc78, 
    env=env@entry=0x7fffffffdc88) at dl-init.c:72
#7  0x00007ffff7de77cb in call_init (env=0x7fffffffdc88, argv=0x7fffffffdc78, argc=1, l=<optimized out>) at dl-init.c:30
#8  _dl_init (main_map=main_map@entry=0xe370a0, argc=1, argv=0x7fffffffdc78, env=0x7fffffffdc88) at dl-init.c:120
#9  0x00007ffff7dec8e2 in dl_open_worker (a=a@entry=0x7fffffffcee0) at dl-open.c:575
#10 0x00007ffff7de7564 in _dl_catch_error (objname=objname@entry=0x7fffffffced0, errstring=errstring@entry=0x7fffffffced8, 
    mallocedp=mallocedp@entry=0x7fffffffcecf, operate=operate@entry=0x7ffff7dec4d0 <dl_open_worker>, 
    args=args@entry=0x7fffffffcee0) at dl-error.c:187
#11 0x00007ffff7debda9 in _dl_open (file=0xe37000 "/usr/lib/x86_64-linux-gnu/unity-control-center-1/panels/libnetwork.so", 
    mode=-2147483647, caller_dlopen=0x7ffff4a70911 <g_module_open+705>, nsid=-2, argc=<optimized out>, argv=<optimized out>, 
    env=0x7fffffffdc88) at dl-open.c:660
#12 0x00007fffeeeedf09 in dlopen_doit (a=a@entry=0x7fffffffd110) at dlopen.c:66
#13 0x00007ffff7de7564 in _dl_catch_error (objname=0x631180, errstring=0x631188, mallocedp=0x631178, 
    operate=0x7fffeeeedeb0 <dlopen_doit>, args=0x7fffffffd110) at dl-error.c:187
#14 0x00007fffeeeee571 in _dlerror_run (operate=operate@entry=0x7fffeeeedeb0 <dlopen_doit>, args=args@entry=0x7fffffffd110)
    at dlerror.c:163
#15 0x00007fffeeeedfa1 in __dlopen (file=<optimized out>, mode=<optimized out>) at dlopen.c:87
#16 0x00007ffff4a70911 in g_module_open () from /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0
#17 0x00007ffff656decb in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#18 0x00007ffff62f06a1 in g_type_module_use () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#19 0x00007ffff656e315 in g_io_modules_load_all_in_directory_with_scope () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#20 0x00007fffdc6f8994 in ?? ()
   from /usr/lib/x86_64-linux-gnu/switchboard/hardware/pantheon-gcc-compatibility/libgcc-sound.so
#21 0x00007ffff62cf149 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#22 0x00007ffff62d0c01 in g_object_newv () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#23 0x00007ffff62d1534 in g_object_new () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
---Type <return> to continue, or q <return> to quit---
#24 0x00007fffdc6f9495 in ?? ()
   from /usr/lib/x86_64-linux-gnu/switchboard/hardware/pantheon-gcc-compatibility/libgcc-sound.so
#25 0x0000000000406d6f in ?? ()
#26 0x0000000000406f6f in ?? ()
#27 0x00007ffff5ff304a in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007ffff5ff33f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007ffff5ff3712 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00007ffff6aa6395 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#31 0x0000000000409632 in ?? ()
#32 0x00007ffff62ca1d4 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#33 0x00007ffff62e49a6 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#34 0x00007ffff62e508f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#35 0x00007ffff65baae6 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#36 0x00007ffff65bacd2 in g_application_run () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#37 0x0000000000409964 in switchboard_main ()
#38 0x00007ffff59f9830 in __libc_start_main (main=0x406b60 <main>, argc=1, argv=0x7fffffffdc78, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdc68) at ../csu/libc-start.c:291
#39 0x0000000000406b99 in _start ()
```

Thanks a lot!

**Comment by Philip-Scott** [comment] 2018-01-24 20:06
Closing as it's a duplicate of #46 :smiley:

**Closed by Philip-Scott** 2018-01-24 20:06 UTC
