### ISSUE TITLE
[Output] speakers for Dell U3818dw screen not available

### ISSUE THREAD

**Issue by mateuspv** [elementary/switchboard-plug-sound#111] opened 2019-03-27 16:09 UTC
I recently brought a dell U3818dw screen that comes with **embed** speakers.
Unfortunately dell does not offer some kinda driver or support to linux, I was wondering if anyone has a work around in order to make the speakers work on Elementary.
I recently tested it on windows and it work fine, no driver or setup required.

My output ports only show "Speakers"(Laptop speakers) or "Headphones"
![Screenshot from 2019-03-27 13-03-24](https://user-images.githubusercontent.com/4995440/55092105-bb560400-5090-11e9-82b7-6c08b8be2bad.png)

I appreciate any info here
Best

**Comment by peteruithoven** [comment] 2019-03-28 01:53
Thanks for the report! I'm afraid this is a duplicate of https://github.com/elementary/switchboard-plug-sound/issues/65
The core issue is that we didn't support sound output to HDMI. 
This has been implemented with: https://github.com/elementary/switchboard-plug-sound/pull/83
But there hasn't been a release that includes this yet. If you  compile the `master` from Github this should work.

**Closed by peteruithoven** 2019-03-28 01:53 UTC

**Comment by peteruithoven** [comment] 2019-03-28 10:19
A new release has been made, should appear in your updates soon.

**Comment by mateuspv** [comment] 2019-03-28 13:14
Hi @peteruithoven , I was not sure if it was released, its working now! Thanks you!
