### ISSUE TITLE
Request to have a volume boost toggle button to allow users to drive volume above 100%

### ISSUE THREAD

**Issue by diddy-boy** [elementary/switchboard-plug-sound#192] opened 2021-05-28 19:39 UTC
## Problem

Request to have a volume boost toggle button to allow users to drive volume above 100%
Other distributions have this as an option. I would assume this is not a hard feature to add

## Proposal

Have the option for the user to toggle this on (off by default) so the user can raise the volume control up to 150%

**Comment by diddy-boy** [comment] 2021-05-28 20:48
A workaround is to change system settings :-
https://elementaryos.stackexchange.com/questions/855/can-i-boost-the-volume-above-100-without-going-into-system-settings

using 'dconf-editor' (not installed by default)  I had to drill down into '/io/elementary/desktop/wingpanel/sound/max-volume' and set max volume to 160
then go to /org/gnome/desktop/sound and Toggle Use Defaults to False
and then Make current value True

This worked but would be good just to enable a toggle option to drive allow the user to drive volume up to 160% in the sound settings view

**Comment by endorama** [comment] 2021-06-09 15:35
A note on suggested workaround: it didn't work for me on elementary Hera until a rebooted (probably logout/login is enough but YMMV).

**Comment by cassidyjames** [comment] 2021-07-07 17:37
Duplicate of #68

**Closed by cassidyjames** 2021-07-07 17:37 UTC
