### ISSUE TITLE
Sound Customization

### ISSUE THREAD

**Issue by PWNL506** [elementary/switchboard-plug-sound#215] opened 2021-11-22 18:53 UTC
### Problem

Sounds can't be edited. Only default sounds can be played.

### Proposal

By adding the setiing of personalizing your sounds, g.e. the Warning sound or the Power Plug-In Sound Elementary can be even more personalizable.

**Comment by danrabbit** [comment] 2021-11-22 18:57
Closing as a duplicate of https://github.com/elementary/switchboard-plug-sound/issues/85

**Closed by danrabbit** 2021-11-22 18:57 UTC
