### ISSUE TITLE
No way to switch bluetooth speaker to A2DP output mode

### ISSUE THREAD

**Issue by matzipan** [elementary/switchboard-plug-sound#40] opened 2017-06-26 20:42 UTC
In the previous plug, on bluetooth speakers, there was a combo box which allowed switching to high-quality A2DP bluetooth mode. There is no way to do this in the current plug.

**Comment by codygarver** [comment] 2017-06-30 10:02
Duplicate of #36

**Closed by codygarver** 2017-06-30 10:02 UTC
